const profanePhrases = [
'2 girls 1 cup',
'a s s',
'a s shole',
'alabama hot pocket',
'alaskan pipeline',
'alligator bait',
'ass monkey',
'auto erotic',
'b a s t a r d',
'b i t c h',
'b o o b',
'baby batter',
'baby juice',
'ball gag',
'ball gravy',
'ball kicking',
'ball licking',
'ball sack',
'ball sucking',
'barely legal',
'beaver cleaver',
'beaver lips',
'beef curtains',
'bi curious',
'big black',
'big breasts',
'big knockers',
'big tits',
'black cock',
'blonde action',
'blonde on blonde action',
'blonde on blonde',
'blow j',
'blow job',
'blow your l',
'blow your load',
'blue waffle',
'bo ob',
'bo obs',
'bounty bar',
'bounty bars',
'brown shower',
'brown showers',
'brunette action',
'bullet vibe',
'bung hole',
'bunny fucker',
'burr head',
'burr heads',
'butt plug',
'c u n t',
'camel jockey',
'camel jockeys',
'camel toe',
'carpet muncher',
'cheese eating surrender monkey',
'cheese eating surrender monkies',
'cheeseeating surrender monkey',
'cheeseeating surrender monkies',
'china swede',
'china swedes',
'ching chong',
'ching chongs',
'chocolate rosebuds',
'christ killer',
'christ killers',
'cleveland steamer',
'clover clamps',
'coon ass',
'coon asses',
'cum face',
'cum licker',
'curry muncher',
'curry munchers',
'date rape',
'dawgie style',
'deep throat',
'deep throating',
'diaper daddy',
'diaper head',
'diaper heads',
'dick pic',
'dirty pillows',
'dirty sanchez',
'dog style',
'doggie style',
'doggy style',
'donkey punch',
'dot head',
'dot heads',
'double dong',
'double penetration',
'douche bag',
'dp action',
'dry hump',
'dumb ass',
'dune coon',
'dune coons',
'eat my ass',
'eat my',
'ethical slut',
'f u c k e r',
'f u c k e',
'f u c k',
'f u k',
'female squirting',
'flipping the bird',
'foot fetish',
'fudge packer',
'gang bang',
'gator bait',
'gay sex',
'giant cock',
'girl on top',
'girl on',
'girls gone wild',
'god dammit',
'god damn',
'god damnit',
'golden shower',
'goo girl',
'gook eye',
'gook eyes',
'group sex',
'h e l l',
'h o m',
'half breed',
'half caste',
'hand job',
'hard core',
'hot carl',
'hot chick',
'how to kill',
'how to murder',
'huge fat',
'jack off',
'jail bait',
'jelly donut',
'jerk off',
'jungle bunnies',
'jungle bunny',
'kwai lo',
'kwai los',
'leather restraint',
'leather straight',
'lemon party',
'make me come',
'male squirting',
'mau mau',
'mau maus',
'moon cricket',
'moon crickets',
'motha fucker',
'motha fuker',
'motha fukkah',
'motha fukker',
'mother fucker',
'mother fukah',
'mother fuker',
'mother fukkah',
'mother fukker',
'mound of venus',
'mr hands',
'muff diver',
'mutha fucker',
'mutha fukah',
'mutha fuker',
'mutha fukkah',
'mutha fukker',
'nig nog',
'nob jokey',
'nsfw images',
'nut sack',
'o c k',
'one cup two girls',
'one guy one jar',
'one guy',
'one jar',
'p e n i s',
'p i s',
'p u s s y',
'pancake face',
'pancake faces',
'phone sex',
'piece of shit',
'piss pig',
'pleasure chest',
'pole smoker',
'pommie grant',
'pommie grants',
'poop chute',
'porch monkey',
'porch monkies',
'pound town',
'prairie nigger',
'prairie niggers',
'prince albert piercing',
'reverse cowgirl',
'rosy palm and her 5 sisters',
'rosy palm',
'round eyes',
'rusty trombone',
's h i t',
's hit',
'sand nigger',
'sand niggers',
'shaved beaver',
'shaved pussy',
'shit ass',
'son of a bitch',
'son of a whore',
'spread legs',
'strap on',
'strip club',
'style doggy',
'suicide girl',
'suicide girls',
'swamp guinea',
'swamp guineas',
't i t',
't i ts',
'take off your',
'tar babies',
'tar baby',
'taste my',
'tea bagging',
'tied up',
'tig ol bitties',
'tig old bitties',
'tight white',
'timber nigger',
'timber niggers',
'to murder',
'tongue in a',
'towel head',
'towel heads',
'tub girl',
'turd burgler',
'two girls one cup',
'udge packer',
'urethra play',
'v a g i n a',
'venus mound',
'violet wand',
'wet dream',
'white power',
'white trash',
'wrapping men',
'wrinkled starfish',
'yellow showers',
];
